server:
  port: 8082

spring:
  application:
    name: fashion-bestseller
  config:
    import: configserver:http://localhost:8888

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: configserver:http://spring-cloud-kubernetes-configserver:8888