---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: hot-deals
      name: hot-deals
    spec:
      ports:
        - name: http
          port: 8083
          targetPort: 8083
      selector:
        app: hot-deals
      type: ClusterIP
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
      name: spring-cloud-kubernetes-configuration-watcher
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
      name: spring-cloud-kubernetes-configuration-watcher:view
    roleRef:
      kind: Role
      apiGroup: rbac.authorization.k8s.io
      name: namespace-reader
    subjects:
      - kind: ServiceAccount
        name: spring-cloud-kubernetes-configuration-watcher
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      namespace: default
      name: namespace-reader
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
        verbs: ["get", "list", "watch"]
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hot-deals-deployment
    spec:
      selector:
        matchLabels:
          app: hot-deals
      template:
        metadata:
          labels:
            app: hot-deals
        spec:
          serviceAccount: spring-cloud-kubernetes-configuration-watcher
          containers:
          - name: hot-deals
            image: springone/hot-deals
            imagePullPolicy: IfNotPresent
            readinessProbe:
              httpGet:
                port: 8083
                path: /actuator/health/readiness
            livenessProbe:
              httpGet:
                port: 8083
                path: /actuator/health/liveness
            ports:
            - containerPort: 8083
