apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: toys-bestseller
build:
#  artifacts:
#  - image: ryanjbaxter/fashion-bestseller
#  tagPolicy:
#    envTemplate:
#      template: "{{.IMAGE_NAME}}:{{.DIGEST_HEX}}"
  artifacts:
  - image: springone/toys-bestseller
    custom:
      buildCommand: "../mvnw clean install"
      dependencies:
        paths:
          - src
          - pom.xml
#  local:

#    jib: {
#           args: ["-Pjib"]
#    }
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
