kind: ConfigMap
apiVersion: v1
metadata:
  name: toys-bestseller
  labels:
    "spring.cloud.kubernetes.config": "true"
data:
  chaos.monkey.enabled: "false"
  chaos.monkey.assaults.latencyActive: "true"