apiVersion: v1
data:
  application.yaml: |-
    spring:
      cloud:
        kubernetes:
          configuration:
            watcher:
              refreshDelay: 10
      rabbitmq:
        username: rbaxter
        password: password
    logging:
      level:
        org:
          springframework:
            cloud:
              kubernetes: TRACE
    management:
      endpoints:
        web:
          exposure:
            include: "*"
kind: ConfigMap
metadata:
  name: spring-cloud-kubernetes-configuration-watcher
